// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_bhar_new_test_output[32] = 
{
-25,  41,  91,  45,  26,  72,  70,  79,  -8, -39,  14,  61,   1,   0, -71,   3, -52,  23,  34, -38, -68, -47,  -2, -58, -55,  17,  -5,  87,  73, -35,  12,  22
};
