// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fc_policy_bhar_bias[5] = 
{
-13359,  10688,   4939,  -7309,  18632
};

const int32_t *const fc_policy_bhar_biases = fc_policy_bhar_bias;
