// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define FC_POLICY_BHAR_W_TYPE INT8
#define FC_POLICY_BHAR_IN_CH 32
#define FC_POLICY_BHAR_OUT_CH 5
#define FC_POLICY_BHAR_PER_CHANNEL_QUANT true
#define FC_POLICY_BHAR_BATCH_SIZE 1
#define FC_POLICY_BHAR_OUT_ACTIVATION_MIN -128
#define FC_POLICY_BHAR_OUT_ACTIVATION_MAX 127
#define FC_POLICY_BHAR_INPUT_BATCHES 1
#define FC_POLICY_BHAR_INPUT_W 1
#define FC_POLICY_BHAR_INPUT_H 1
#define FC_POLICY_BHAR_DST_SIZE 5
#define FC_POLICY_BHAR_ACCUMULATION_DEPTH 32
#define FC_POLICY_BHAR_INPUT_OFFSET 128
#define FC_POLICY_BHAR_OUTPUT_OFFSET -13
