// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fc_policy_bhar_input_tensor[32] = 
{
  47,   69,   23,  108, -123,  -45,  -16,  -49,  123,   33,    3,    2,   95,   46, -124, -106,   78,  -78,   65,  -33,  -10,   59,  -16,  -37,  -42,   66,   25,  -18,  103,   43,  102,  -25
};
