// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fc_policy_bhar_output[5] = 
{
  39,  102,   86,   95,   29
};

const int8_t *const fc_policy_bhar_output_ref = fc_policy_bhar_output;
