// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fc_policy_bhar_output_multiplier[5] = 
{
 2103497601,  2142967158,  1108120750,  1108930847,  1108584563
};

const int32_t *const fc_policy_bhar_output_mult = fc_policy_bhar_output_multiplier;
