// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_cell_gate_bias[32] =
{
  -142,
  -28134,
  -20777,
  -1024,
  -14899,
  27594,
  27272,
  17781,
  21532,
  -7374,
  22272,
  3645,
  -27247,
  6429,
  -30670,
  -16295,
  -30715,
  20900,
  -27869,
  13656,
  4159,
  7550,
  -31227,
  -11234,
  -32100,
  -16848,
  28776,
  -1468,
  16599,
  -27267,
  -7739,
  26282
};
