// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_forget_gate_bias[32] =
{
  -16697,
  -15769,
  -21310,
  7284,
  22267,
  6179,
  -21511,
  -23880,
  -16689,
  -30682,
  -30421,
  5278,
  25545,
  -15330,
  -12428,
  19551,
  5967,
  15324,
  -25196,
  -29999,
  17037,
  12998,
  19826,
  -28886,
  -17788,
  24786,
  26792,
  -29013,
  -18603,
  -24513,
  -25834,
  19694
};
