// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_input_to_input_eff_bias[32] =
{
  18089,
  -3235,
  -25960,
  35608,
  30547,
  17461,
  16833,
  20693,
  -70785,
  -17851,
  -6099,
  -4347,
  16990,
  -3856,
  -7239,
  -33731,
  21337,
  4285,
  17060,
  9094,
  -23660,
  -14840,
  28224,
  17736,
  19778,
  48671,
  -38842,
  36586,
  8864,
  44786,
  -13835,
  -29646
};
