// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_input_to_output_eff_bias[32] =
{
  7720,
  118,
  -45551,
  17544,
  3934,
  -24437,
  11592,
  -10623,
  12247,
  -20345,
  10447,
  -25258,
  -22519,
  -11777,
  -27032,
  -25939,
  13376,
  -22489,
  526,
  -47887,
  25995,
  -33097,
  48431,
  -4389,
  -58467,
  38303,
  24533,
  35175,
  36180,
  18769,
  -20374,
  -45648
};
