// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_input_gate_bias[32] =
{
  26665,
  7901,
  -15976,
  27160,
  30547,
  -1355,
  -11199,
  22485,
  -24961,
  6981,
  -28883,
  1925,
  19422,
  240,
  -5447,
  -21443,
  9689,
  -1091,
  21540,
  29446,
  -3308,
  -5112,
  17984,
  32328,
  18754,
  21023,
  -6330,
  24042,
  -1888,
  24562,
  2805,
  -5582
};
