// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_input_to_forget_eff_bias[32] =
{
  -25017,
  -18585,
  -39102,
  -2316,
  14715,
  31651,
  -13319,
  -32968,
  19791,
  -42330,
  -50901,
  -4066,
  -1335,
  5406,
  -15628,
  -4129,
  13007,
  24540,
  -24684,
  -47279,
  19597,
  25158,
  12402,
  -13654,
  -44284,
  24402,
  53544,
  -46165,
  9685,
  4799,
  -12522,
  11886
};
