// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_input_to_cell_eff_bias[32] =
{
  -21902,
  -55398,
  -4137,
  -23808,
  -23219,
  19274,
  65544,
  57461,
  26012,
  -7886,
  15360,
  -13891,
  -38127,
  -2147,
  -57550,
  -26919,
  -22267,
  6052,
  -53725,
  19928,
  -28225,
  16638,
  -35195,
  -45154,
  -56036,
  -5712,
  33256,
  -6204,
  -1705,
  -68355,
  4933,
  38570
};
