// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_output_gate_bias[32] =
{
  -5464,
  27510,
  -24047,
  27144,
  15454,
  -21365,
  2760,
  12673,
  1367,
  21767,
  24271,
  -17578,
  -31479,
  4479,
  -22808,
  -29779,
  16320,
  -2137,
  25998,
  -23695,
  18059,
  -11081,
  24879,
  -8741,
  -24163,
  14111,
  14421,
  21095,
  19540,
  6353,
  -27414,
  -14544
};
