// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_bhar_output_ref[32] =
{
  -43,
  -53,
  12,
  -78,
  -48,
  14,
  81,
  87,
  21,
  19,
  63,
  -28,
  -25,
  -6,
  -14,
  10,
  -78,
  30,
  -55,
  26,
  -25,
  20,
  -107,
  -68,
  -13,
  -81,
  38,
  -8,
  -7,
  -93,
  8,
  17
};
