// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_recurrent_to_forget_eff_bias[32] =
{
  2170,
  -910,
  400,
  3330,
  1150,
  6110,
  2320,
  -270,
  1740,
  3780,
  3130,
  -880,
  -3800,
  5280,
  -2580,
  -2170,
  -1110,
  -910,
  2130,
  -1530,
  -3450,
  1640,
  8120,
  -6110,
  -3670,
  -3960,
  2510,
  5630,
  -580,
  2430,
  1340,
  3550
};
