// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_recurrent_to_output_eff_bias[32] =
{
  -7580,
  830,
  -670,
  -6030,
  -340,
  1370,
  1020,
  5580,
  -1770,
  5330,
  7260,
  -6260,
  -6170,
  -1440,
  -4710,
  5690,
  -4780,
  -2630,
  2290,
  -5430,
  540,
  1580,
  9290,
  810,
  5620,
  5120,
  1070,
  -880,
  -1830,
  -3680,
  -3190,
  -3260
};
