// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_recurrent_to_cell_eff_bias[32] =
{
  -7270,
  1970,
  -2890,
  1980,
  2580,
  760,
  -15470,
  -4300,
  -2350,
  9550,
  -8650,
  2230,
  1340,
  -130,
  -5440,
  -770,
  5490,
  4600,
  2000,
  -720,
  -3730,
  1960,
  2720,
  1460,
  4270,
  -1950,
  3200,
  -4010,
  -12270,
  6040,
  -2680,
  -880
};
