// Generated by test_settings.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_bhar_recurrent_to_input_eff_bias[32] =
{
  2440,
  320,
  -4110,
  6230,
  -1090,
  7010,
  7790,
  -3060,
  -5330,
  -1940,
  1270,
  1050,
  1360,
  3040,
  3870,
  -3080,
  2170,
  -3350,
  -590,
  -2900,
  -2820,
  2310,
  4830,
  3080,
  1330,
  2040,
  -3690,
  7350,
  1710,
  2720,
  2840,
  3920
};
