// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_bhar_output[32] = 
{
  63,  127,  127,  127,   98,  113,  127,  127,  127,   78,  119,  127,   76,  116,  127,  127,   57,  127,  127,   95,   98,  127,  127,  127,   43,  127,  127,  127,  101,  127,   84,  114
};
