// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fc_classifier_bhar_bias[20] = 
{
 17822,  -7577, -22429,  26965, -16153, -15758,  -7135, -27804, -17750,   4791,  21621, -13748,  18778,   1515, -12086,   7997,   6801, -30435,  25437,  33025
};

const int32_t *const fc_classifier_bhar_biases = fc_classifier_bhar_bias;
