// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fc_classifier_bhar_input_tensor[32] = 
{
-114, -102,  -12,   23,  -67,  -59,  114,  -97,  113,   67,  -11,  126,   16,  -68,  -81,  114, -112,  -86,  -65,   53,  -17,   -1,  -39,  -57,   70,   -5,  103,  -18, -110,   45,   59,  -40
};
