// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fc_classifier_bhar_output_multiplier[20] = 
{
 1143557486,  2033970763,  1131624672,  1134407928,  1139781039,  1145140650,  1139921053,  1132981331,  1142951301,  1133059749,  1136559221,  1144685739,  1139601544,  1139795284,  2137280576,  1143300929,  1144688046,  1128833954,  1144739873,  1121661011
};

const int32_t *const fc_classifier_bhar_output_mult = fc_classifier_bhar_output_multiplier;
