// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fc_classifier_bhar_output[20] = 
{
  17,   58,  -31,   35,    7,   26,    5,   55, -122,  -41,  -67,  -22,   80,   -6,  -82,  -55,  105, -105,   15,   10
};

const int8_t *const fc_classifier_bhar_output_ref = fc_classifier_bhar_output;
