// Generated by generate_test_data.py using tensorflow version 2.15.0).
// Interpreter from tensorflow version 2.15.0 and revision v2.15.0-rc1-8-g6887368d6d4.
#pragma once
#include <stdint.h>

const int32_t Classifier_layer_3_fully_connected_bias[6] =
{
  474,
  395,
  119,
  -105,
  -392,
  -223
};
