// Generated by generate_test_data.py using tensorflow version 2.15.0).
// Interpreter from tensorflow version 2.15.0 and revision v2.15.0-rc1-8-g6887368d6d4.
#include "output_ref_data.h"
#include "layer_2_fully_connected_config_data.h"
#include "layer_2_fully_connected_bias_data.h"
#include "layer_2_fully_connected_weights_data.h"
#include "layer_1_fully_connected_config_data.h"
#include "layer_1_fully_connected_bias_data.h"
#include "layer_1_fully_connected_weights_data.h"
#include "layer_0_fully_connected_config_data.h"
#include "layer_0_fully_connected_bias_data.h"
#include "layer_0_fully_connected_weights_data.h"
#include "input_data.h"
